name = "handle-language"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-02-17"

[build]
command = "yarn worker:build"
[build.upload]
format = "service-worker"
