declare const styles: {
  readonly "hljs": string;
  readonly "hljs-addition": string;
  readonly "hljs-attribute": string;
  readonly "hljs-built_in": string;
  readonly "hljs-bullet": string;
  readonly "hljs-comment": string;
  readonly "hljs-deletion": string;
  readonly "hljs-emphasis": string;
  readonly "hljs-keyword": string;
  readonly "hljs-link": string;
  readonly "hljs-literal": string;
  readonly "hljs-meta": string;
  readonly "hljs-name": string;
  readonly "hljs-number": string;
  readonly "hljs-params": string;
  readonly "hljs-quote": string;
  readonly "hljs-regexp": string;
  readonly "hljs-section": string;
  readonly "hljs-selector-class": string;
  readonly "hljs-selector-id": string;
  readonly "hljs-selector-tag": string;
  readonly "hljs-string": string;
  readonly "hljs-strong": string;
  readonly "hljs-symbol": string;
  readonly "hljs-tag": string;
  readonly "hljs-template-variable": string;
  readonly "hljs-title": string;
  readonly "hljs-type": string;
  readonly "hljs-variable": string;
};
export = styles;

