name: Continuous Integration workflow

on:
    workflow_call:

jobs:
    warmup_dependencies_cache:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

    format_check:
        needs:
            - warmup_dependencies_cache
        runs-on: ubuntu-latest
        timeout-minutes: 3
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - name: Check code formatting
              run: pnpm run format:check

    lint:
        needs:
            - warmup_dependencies_cache
        runs-on: ubuntu-latest
        timeout-minutes: 3
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - name: Run Linter in this repository
              run: pnpm run lint

    test:
        needs:
            - warmup_dependencies_cache
        runs-on: ubuntu-latest
        timeout-minutes: 10
        env:
            NODE_ENV: development
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - name: Run tests
              run: pnpm run test

    build:
        needs:
            - warmup_dependencies_cache
        runs-on: ubuntu-latest
        timeout-minutes: 10
        env:
            NODE_ENV: production
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - name: Build applications
              run: pnpm run build
