name: Continuous Integration on Pull Request

on:
    pull_request:
        branches:
            - main
        types: [opened, synchronize, reopened, ready_for_review]

# Cancel in-progress runs for the same PR
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        if: github.event.pull_request.draft == false
        uses: ./.github/workflows/ci.yml