# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: "!master"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt update
    - name: Install utilities
      run:
        sudo apt install -y automake build-essential git libgbm1 pkg-config
        python python-pip unzip
    - name: Use Node.js "12.x"
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: yarn install --frozen-lockfile
    - run: yarn run perf --target=${GITHUB_REF##*/}
